# Generated by Django 3.2.3 on 2021-06-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
