# Generated by Django 3.2.3 on 2021-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail_link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
