# Generated by Django 3.2.3 on 2021-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipper', '0002_auto_20210722_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_link',
            field=models.URLField(max_length=500),
        ),
    ]
