# Generated by Django 3.2.3 on 2021-07-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clipper', '0003_alter_course_course_link'),
        ('clipper', '0003_alter_course_thumbnail_link'),
    ]

    operations = [
    ]
